### ISSUE TITLE
Algorithm for competative coding 

### ISSUE THREAD

**Issue by ArbitCode** [technojam/Ultimate_Algorithms_Repository#1]
For a competitive coder, they are not able to find "how and from where should we start" at GU. When I was in the first year, I was confused about what should do or leave. If Technojam starts a GitHub repository dedicated to the competitive coder and its opportunity.

**Comment by danishjamal104** [comment]
For a starting guide, you can visit the [developer-roadmap/dsa](https://github.com/technojam/developer-roadmap/tree/master/Data%20Structures%20And%20Algorithms), where we have resources to get started in different domains.
