### ISSUE TITLE
String ATOI implementation

### ISSUE THREAD

**Issue by VinWare** [technojam/Ultimate_Algorithms_Repository#109]
**Title or Name of the Algorithm**
* ATOI for C++ string

**Describe the algorithm**
Converts a string to int, counting only the leading valid characters (digits or sign). Ignores leading spaces. Assumes string fits in given size of int (overflows if string is too big).

**Comment by aayushwadhwa1** [comment]
Can I take up this?

**Comment by shushriya6998** [comment]
Hi,

I am interested in solving this. Can I solve this?

**Comment by VinWare** [comment]
Mate I just made a pull request. This issue was for my PR

**Comment by VinWare** [comment]
See you can look into other algos in the String folder. Create your own issue and make a PR
