### ISSUE TITLE
[NEW Algorithm]

### ISSUE THREAD

**Issue by CoderSaty** [technojam/Ultimate_Algorithms_Repository#121]
**Title or Name of the Algorithm**
* Juggling Algorithm

**Describe the algorithm**
The algorithm rotates the arr[] of size n by d elements.
Time complexity:- O(n)
Space Complexity:- O(1)

**Comment by aayushwadhwa1** [comment]
Can I work on this?

**Comment by shushriya6998** [comment]
I would like to work on this using C++. Please assign. Thanks!

**Comment by princekalra** [comment]
hey can i contribute on this

**Comment by Namanmittal0007** [comment]
@CoderSaty  I would like to be assigned with this task, I can implement juggling algorithm which rotates the arr[] of size n by d elements
Time complexity=O(n)
Space complexity=O(1)

**Comment by aayushwadhwa1** [comment]
I have created a Pull Request, can you please check

**Comment by aayushwadhwa1** [comment]
and can you tell me how to link pull request to an issue?

**Comment by Namanmittal0007** [comment]
> and can you tell me how to link pull request to an issue?

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue, Hope this helps.
