### ISSUE TITLE
Stacks and its associated functions

### ISSUE THREAD

**Issue by dalalvarun** [technojam/Ultimate_Algorithms_Repository#122]
18)Stacks

- Stack implementation using array
- Stack implementation using Linked List
- Multiple Stack
- Parenthesis Checker
- Infix to Postfix
- Infix to Prefix
- Prefix evaluation
- Postfix Evaluation

I can do this. Please assign to me

**Comment by AyushRajSharma** [comment]
i can do this please assign me

**Comment by dalalvarun** [comment]
@technojam Please assign it to mee
