### ISSUE TITLE
Traversal of a 2D matrix in a clockwise spiral

### ISSUE THREAD

**Issue by MohakChugh** [technojam/Ultimate_Algorithms_Repository#123]
## Traversal of a 2D matrix in a clockwise spiral

Given a 2D array, Traverse the array in a spiral form. 
See the following examples.

Examples: 
```
Input: 
        1    2   3   4
        5    6   7   8
        9   10  11  12
        13  14  15  16
Output: 1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10 
Explanation: The output is matrix in spiral format. 

Input:  
        1   2   3   4  5   6
        7   8   9  10  11  12
        13  14  15 16  17  18
Output: 1 2 3 4 5 6 12 18 17 16 15 14 13 7 8 9 10 11
```
Explanation :The output is matrix in spiral format.

**Comment by vortex2099** [comment]
Can you assign me this problem?

**Comment by shushriya6998** [comment]
I want to contribute to this issue. Will be using C++. Please assign me. Thanks!

**Comment by kgolder92** [comment]
Can I work on this? I solved this problem in JavaScript

**Comment by Anmol55555** [comment]
please assign me this problem. Thanks.!
