### ISSUE TITLE
Extended Euclids Algo

### ISSUE THREAD

**Issue by vinaypathak07** [technojam/Ultimate_Algorithms_Repository#142]
**Title or Name of the Algorithm**
* Extended Euclids Algo

**Describe the algorithm**

- Extended Euclidean algorithm finds integer coefficients x and y such that:

  ax + by = gcd(a, b) 

- It is also used to find multiplicative modulo inverse of a w.r.t  b

**Comment by vinaypathak07** [comment]
I would like to work on it.

**Comment by Trinadh21** [comment]
I would love to work on this issue, I have experience in programming in languages in C,C++ for quite a long time. Please add me to this issue.

**Comment by princekalra** [comment]
i want to work  on this please assign it to me
