### ISSUE TITLE
0/1 KnapSack algorithm | Dynamic Programming

### ISSUE THREAD

**Issue by tejasbirsingh** [technojam/Ultimate_Algorithms_Repository#143]
**Title or Name of the Algorithm**
* 0/1 KnapSack Algorithm using Dynamic Programming in C++

**Describe the algorithm**
0/1 Knapsack is very important problem which creates the base for dynamic programming using which you can solve various problems such as Subset Sum Problem,Equal Sum Partition Problem. 
In 0/1 knapsack problem we are a sack and some items and we have to add items in sack but sack's capacity is bounded by certain weight and we can't add more items than weight of knapsack. We are given items weight and profit array and target is to maximize the profit. 0/1 means either we can include the item or not.

**Comment by tejasbirsingh** [comment]
Please assign this to me! I will write clean code and write the comments for every line to explain it . Thanks

**Comment by tusharsbauskar** [comment]
I would like to work on this. Kindly assign me this issue.

**Comment by rudrajit1729** [comment]
I would like to implement the algorithm in Python and C along with CPP. Kindly assign this to me. Thanks.

**Comment by aishwarya-45** [comment]
I can explain this algo explicitly and write well commented code using top-down and bottom-up approach both. Please assign this task to me. Thanks.

**Comment by rudrajit1729** [comment]
@tejasbirsingh Kindly allot the task. I have finished the task and would like to contribute here once allowed.

**Comment by princekalra** [comment]
i want to work  on this please assign it to me

**Comment by roastedcoder** [comment]
I can explain 0/1 knapsack and all it's variations with intuition behind to solve those problem mentioned.
