### ISSUE TITLE
Rotated Sorted Array Search

### ISSUE THREAD

**Issue by yashasvi25** [technojam/Ultimate_Algorithms_Repository#144]
Rotated Sorted Array Search using Binary Search

Given an array of integers A of size N and an integer B. Array A is rotated at some pivot unknown to us beforehand.A target value B is given to search. If found in the array, the algorithm return its index, otherwise return -1.

**Comment by yashasvi25** [comment]
I would like to work on this. Please assign me this issue.

**Comment by Manavi18** [comment]
I can implement this is python.

**Comment by panktishah62** [comment]
I can implement this in C/C++/Python/Java. Please assign this to me.

**Comment by Renu-code** [comment]
I want to work on this issue.  Please assign it to me ??
