### ISSUE TITLE
Add Basic Programs

### ISSUE THREAD

**Issue by shreyanshdeep** [technojam/Ultimate_Algorithms_Repository#15]
Add some basic algorithms to the  basic algorithms folder. Some sample programs are given below. 

- **Check whether a number is prime or not**
- **Check whether a given string is plaindrome**
- **Count the frequency of all characters in a string**
- **Sum of all elements in an array**
- **Sum of diagonal elements of matrix of size n*n**
- **Print nth Fibonacci number**
- **Subtract 2 Matrix**
- **Print the table of nth number**
- **Check if a number is a perfect square**

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by CodeSadhu** [comment]
@shreyanshdeep I'd like to take this up! Can you please assign it to me?

**Comment by icecreamcake101** [comment]
i'd like to work on this too

**Comment by iayushguptaaa** [comment]
hey @shreyanshdeep  I'd would like to contribute , Can you please assign it to me ?

**Comment by Rituraj-commits** [comment]
Hello @shreyanshdeep  would love to work on this issue and make it more efficient. Looking Forward.

**Comment by noman2002** [comment]
I'd like to work on it. Please assign it to me .

**Comment by yashaswinipai** [comment]
I'd like to work on it. Can you please assign it to me?

**Comment by officiallysidsingh** [comment]
I would like to work on this. Please assign it to me.

**Comment by Rishabhkapoor** [comment]
I'd like to work on it. Please assign it to me.

**Comment by 180Gio** [comment]
@shreyanshdeep I would like to work on this. Could you assign this to me please?

**Comment by Tanishqpundir24510** [comment]
@shreyanshdeep  I would like  to do  work on  it. Can you please assign this to me?

**Comment by sayush865** [comment]
hi, can i work on it?

**Comment by nits01** [comment]
I would like to work on this.

**Comment by tanishq-agarwal** [comment]
Can I take this one?

**Comment by iamatul45** [comment]
Can I contribute to it?

**Comment by ghost** [comment]
I would like contribute in this. Please assign me the issue.

**Comment by devanshi-katyal** [comment]
I would like to work on an issue!

**Comment by guptaa98** [comment]
I would like to work on an issue. Please assign me one

**Comment by Codedude1** [comment]
Is it still open? I want to contribute.
