### ISSUE TITLE
Lowest Common Ancestor in Binary-Tree

### ISSUE THREAD

**Issue by ashutoshkumar6** [technojam/Ultimate_Algorithms_Repository#151]
*LCA**
* Lowest Common Ancestor in Binary-Tree

Let T be a rooted tree. The lowest common ancestor between two nodes n1 and n2 is defined as the lowest node in T that has  both n1 and n2 as descendants.

**Comment by pranjalkumar153** [comment]
Please assign this task to me.

**Comment by aishwarya-45** [comment]
Kindly assign this task to me. I can explicitly explain the complete algo with well commented code in C++.

**Comment by princekalra** [comment]
i want to work  on this please assign it to me
