### ISSUE TITLE
[Karp-Rabin String Matching Algorithm]

### ISSUE THREAD

**Issue by rudrajit1729** [technojam/Ultimate_Algorithms_Repository#156]
**Title or Name of the Algorithm**
* Karp Rabin String Matching Algorithm

**Describe the algorithm**
Given a text and a pattern,  write a function that prints all occurrences of pattern in text. 
Karp-Rabin algorithm slides the pattern one by one like the naive algorithm. But unlike the Naive algorithm, it matches the hash value of the pattern with the hash value of current substring of text, and if the hash values match then only it starts matching individual characters.

**Comment by rudrajit1729** [comment]
I would like to be assigned

**Comment by rudrajit1729** [comment]
I would like to work on this

**Comment by rudrajit1729** [comment]
Please assign this to me

**Comment by princekalra** [comment]
i want to work  on this please assign it to me

**Comment by rudrajit1729** [comment]
Sure. Go ahead.
