### ISSUE TITLE
[Pigeonhole Sorting]

### ISSUE THREAD

**Issue by aishwarya-45** [technojam/Ultimate_Algorithms_Repository#158]
**Title or Name of the Algorithm**
* Pigeonhole Sorting

**Describe the algorithm**
Pigeonhole sorting is a sorting algorithm that is suitable for sorting lists of elements where the number of elements and the number of possible key values are approximately the same.
It requires O(n + Range) time where n is the number of elements in the input array and ‘Range’ is a number of possible values in the array.

**Comment by aishwarya-45** [comment]
I would like to work on this issue. Can I work?

**Comment by Manavi18** [comment]
I can implement this in python.

**Comment by akshat235** [comment]
Please assign this to me.

**Comment by princekalra** [comment]
i want to work  on this please assign it to me

**Comment by Renu-code** [comment]
I can implement this...can you assign this issue to me??
