### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by vishal-bhola** [technojam/Ultimate_Algorithms_Repository#165]
**Title or Name of the Algorithm**
* Bubble Sort

**Describe the algorithm**
Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in wrong order.

**Comment by ymchandaliya** [comment]
@VersatileVishal I would like to work on this. Please assign this to me. I can implement it in C, C++, Python, Java

**Comment by vishal-bhola** [comment]
@ymchandaliya  Only the maintainer of this repo can assign although i have implemented this in C already.

**Comment by vishal-bhola** [comment]
@shreyanshdeep i have already made a PR for this. Please, assign it to me and now you can close the PR as well.

**Comment by zahinekbal** [comment]
@VersatileVishal I would like to work on this issues please assign it to me  I want to Implement BUBBLE_SORT with C++ STL 
using comparator function......

**Comment by vishal-bhola** [comment]
@zahinekbal i think only the maintainer can assign.

**Comment by zahinekbal** [comment]
So how we will know who is maintainer  for assigning the task ..

**Comment by zahinekbal** [comment]
@shreyanshdeep I added BubbleSort_STL.C++ ,used comparator function..
please check my code & review my PR

**Comment by Sayantan-world** [comment]
Can u assign it to me? want to do it in Python.

**Comment by princekalra** [comment]
i want to work  on this please assign it to me

**Comment by SMITVASOYA** [comment]
I want to contribute it please assign @VersatileVishal.

I will implement using c language.

**Comment by sejalrastogi** [comment]
I want to work on this. I will implement this in Java.

**Comment by gaurangisinha** [comment]
Hello, @VersatileVishal I want to do this in JavaScript, could you please assign this to me.
