### ISSUE TITLE
GCD(Euclidean algorithm)

### ISSUE THREAD

**Issue by Bijoy-007** [technojam/Ultimate_Algorithms_Repository#17]
May i work on this?

**Comment by shreyanshdeep** [comment]
Please use the template for your issue

**Comment by shreyanshdeep** [comment]
Yes sure but please give a brief description about it too. :)

**Comment by sayush865** [comment]
Hi, Can i work on it?

**Comment by Bijoy-007** [comment]
I opened a PR 
Please review

**Comment by danishjamal104** [comment]
@Bijoy-007 
There is no PR linked with this issue, kindly do the same. And be more descriptive about the issue, update the title and comment for the same.

**Comment by Bijoy-007** [comment]
Please specify the folder so that I can open a PR

**Comment by Harshsngh07** [comment]
Is this still open?

**Comment by Bijoy-007** [comment]
Please check PR

**Comment by sakshi0461** [comment]
@Bijoy-007 Can you please assign this issue to me?

**Comment by Bijoy-007** [comment]
@sakshi0461 I already opened a PR for this one

**Comment by MohakChugh** [comment]
I've added a PR for this, Please review

**Comment by Bijoy-007** [comment]
@MohakChugh I was assigned for this one
