### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by Zeeshan-2k1** [technojam/Ultimate_Algorithms_Repository#177]
**Heap Sort**

**Description**
Heap sort is a comparison based sorting technique based on Binary Heap data structure. It is similar to selection sort where we first find the maximum element and place the maximum element at the end. We repeat the same process for the remaining elements.

**Comment by CoderSaty** [comment]
I can do it with C++ please assign it to me.

**Comment by prabhdeepsingh3499** [comment]
I can do it in python, please assign it to me.

**Comment by coding-sourabh** [comment]
I wil implement in CPP , please assign it to me

**Comment by himik-nainwal** [comment]
I want to do with python 3 please assign me.

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by MeetMangukiya7** [comment]
I would love to do this. Also I Have depth knowledge in data structure and algorithm.
