### ISSUE TITLE
[NEW Algorithm] N-Queen problem

### ISSUE THREAD

**Issue by sarveshvhawal007** [technojam/Ultimate_Algorithms_Repository#193]
**BackTracking Algorithm**
* Famous N-Queen Problem

**Describe the algorithm**
When Given a number n as input
It outputs the number of ways of arranging queens in that NxN chessboard such that no two queens can kill each other.

for eg: n=4
there are two possible ways which are outputted like this-
---------------------------
.Q..
...Q
Q...
..Q.
---------------------------
..Q.
Q...
...Q
.Q..
---------------------------

Can I work on this problem

**Comment by sarveshvhawal007** [comment]
Please Assign it to me... 
I have pulled the request and made the necessary changes

**Comment by sumitk63** [comment]
Can i work on this?

**Comment by Capt-Titanium** [comment]
I can send a PR now. please assign.

**Comment by chiillax** [comment]
Could you please assign me for this task ?
