### ISSUE TITLE
Bellman-Ford Algorithm

### ISSUE THREAD

**Issue by Subhas-08** [technojam/Ultimate_Algorithms_Repository#197]
Bellman-Ford Algorithm

It's a simplest Graph algorithm to find shortest path. It can be work in negative weight edges also

**Comment by Prod-IP** [comment]
may I work on this issue ??

**Comment by coding-sourabh** [comment]
please assign this to me

**Comment by Subhas-08** [comment]
@Prodip-Kumar-Paul  yaeh

**Comment by Subhas-08** [comment]
@coding-sourabh  sorry this given to someone ,plz go with another issue or add new issue
