### ISSUE TITLE
[Kadane's Algorithm]

### ISSUE THREAD

**Issue by zahinekbal** [technojam/Ultimate_Algorithms_Repository#204]
**Title or Name of the Algorithm**
* Kadane's Algorithn 

**Describe the algorithm**
Kadane's algorithm is a Dynamic Programming approach to solve “the largest contiguous elements in an array” with  O(n) runtime complexity and O(1) space.

**Comment by Uyadav207** [comment]
@zahinekbal , please assign this to me.

**Comment by rahulsawlani22** [comment]
I know this well, do I just have to write a program for it?
assign it to me.

**Comment by manan2110** [comment]
Please assign this one to me. I am a beginner And I can work on this , I know it well.
