### ISSUE TITLE
[Minimum spanning tree - Prim's algorithm]

### ISSUE THREAD

**Issue by BetaZeon** [technojam/Ultimate_Algorithms_Repository#212]

**Comment by gunjan543** [comment]
I want to contribute in this

**Comment by gunjan543** [comment]
I created a pull request.

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by gunjan543** [comment]
Please review my pull request.

**Comment by BetaZeon** [comment]
> 
> 
> Please review my pull request.

Reviewed and merged.

**Comment by BetaZeon** [comment]
> 
> 
> Could you please assign me for this task ?

Assigning you the issue but try it with the different way.

**Comment by chiillax** [comment]
Please review & merge #296
