### ISSUE TITLE
Add algorithms for bit manipulation

### ISSUE THREAD

**Issue by pathak-abhinav** [technojam/Ultimate_Algorithms_Repository#218]
**Title or Name of the Algorithm**
Brian Kernighan's ALgorithm

**Describe the algorithm**
A simple yet efficient algorithm that counts no. of set/high bits in an unsigned integer.

**Comment by zatch3301** [comment]
Can i work on this?

**Comment by pathak-abhinav** [comment]
please review the PR#219

**Comment by pathak-abhinav** [comment]
Please review the new PR#292.

**Comment by pathak-abhinav** [comment]
I hope I have linked the PR to the issue properly this time, Is there still any problem in merging?
