### ISSUE TITLE
GREEDY ALGORITHM | | Money Problem

### ISSUE THREAD

**Issue by Abhishek-7017** [technojam/Ultimate_Algorithms_Repository#221]
In this problem, we will use a greedy algorithm to find the minimum number of coins/ notes that could makeup to the given sum. For this we will take under consideration all the valid coins or notes i.e. denominations of { 1, 2, 5, 10, 20, 50 , 100, 200 , 500 ,2000 }. And we need to return the number of these coins/notes we will need to make up to the sum.

Example-
    Input : 1231
    Output : 7

We will need two Rs 500 notes, two Rs 100 notes, one Rs 20 note, one Rs 10 note and one Re 1 coin.
That sums to 2+2+1+1+1 = 7

Example-
    Input : 2150
    Output : 3

**Comment by Ace117MC** [comment]
Please assign this to me .
And 1st example have answer 6 - 500+500+200+20+10+1

**Comment by sachajoy** [comment]
@Abhishek-7017 please assign it to me
c++ or python any language

**Comment by verma-pulkit** [comment]
Assign this to me, i can do this

**Comment by SamarthMayya** [comment]
This problem can be easily solved by using a dp array... Are we given the constraint on the total sum?

**Comment by SamarthMayya** [comment]
If the total sum is of the order 1e5-1e7, then it can be solved by means of a dp very fast
