### ISSUE TITLE
[BUG] Readme file required changes in Pull Request Section

### ISSUE THREAD

**Issue by danishjamal104** [technojam/Ultimate_Algorithms_Repository#225]
### Description
Delete [.DS_Store](https://github.com/technojam/Ultimate_Algorithms_Repository/blob/master/.DS_Store) file.
Update [Reame.md](https://github.com/technojam/Ultimate_Algorithms_Repository/blob/master/README.md#pull-request-process) file.

**Comment by shreyanshdeep** [comment]
Reopening this issue because I feel there are more changes needed to be made to the readme.md file.
