### ISSUE TITLE
[NEW Algorithm]Divide and Conquer Algorithm

### ISSUE THREAD

**Issue by Anushka-codergirl** [technojam/Ultimate_Algorithms_Repository#231]
**Divide and Conquer Algorithm**
* Divide and Conquer Algorithm

**Describe the algorithm**
A divide and conquer algorithm is a strategy of solving a large problem by 
1.breaking the problem into smaller sub-problems 
2.solving the sub-problems, and 
3.combining them to get the desired output.

**Comment by Rishabrp99** [comment]
Hey @Anushka-codergirl ,this is Rishab here ,Can you assign this to me this is my first time contributing to open source.

**Comment by gaurangisinha** [comment]
Hello @Anushka-codergirl, this is the first time I am contributing to open source and I am very keen on contributing to this issue. Please assign it to me.

**Comment by harshitgupta2000** [comment]
@Anushka-codergirl please assign it to me
