### ISSUE TITLE
[Linked-List] FAANG Interview Questions

### ISSUE THREAD

**Issue by Uyadav207** [technojam/Ultimate_Algorithms_Repository#233]
**Linked-List Questions*

**Describe the algorithm**

- Contributing Linked-List Questions
  
## Area covered 

- [x] Implementations
- [x] Interview Questions
- [x] No of question : 15

**Comment by Samridhi-98** [comment]
Added a solution of add two numbers please check.

**Comment by shikhar8434** [comment]
Added Two Linked lists problems, counting nodes and max &min #241
