### ISSUE TITLE
Linked List basic functions[NEW Algorithm]

### ISSUE THREAD

**Issue by Kirtiahuja** [technojam/Ultimate_Algorithms_Repository#242]
**Basic functions:adding a node,subtracting a node etc**
Linked list function
**Helps in understanding the basic operations to be performed on linked list**
knowing basic linked list functions would make better understanding of data structures

**Comment by Oreo-san** [comment]
May I start working on this @Kirtiahuja? Would be happy to contribute :smiley:

**Comment by shikhar8434** [comment]
I would love to contribute too

**Comment by garimamishraa** [comment]
I would wanna contribute

**Comment by Kirtiahuja** [comment]
Made a PR on issue number #242
