### ISSUE TITLE
Sudoku Solver backtracking

### ISSUE THREAD

**Issue by ShristiAgrawal** [technojam/Ultimate_Algorithms_Repository#251]
**Title or Name of the Algorithm**
* Sudoku solver

**Describe the algorithm**
Solves the 9*9 sudoku with backtracking(Accepted on leetcode)
[sudoku solver.docx](https://github.com/technojam/Ultimate_Algorithms_Repository/files/5324141/sudoku.solver.docx)

**Comment by chiillax** [comment]
Could you please assign me for this task ?
