### ISSUE TITLE
Circular Queue Implementation[NEW Algorithm]

### ISSUE THREAD

**Issue by gargig412** [technojam/Ultimate_Algorithms_Repository#252]
**Implementation of Circular Queue** 

_A queue is an abstract data structure that contains a collection of elements._

- A circular queue is a kind of queue in which the last position is connected to the first position just to make a complete circle. It implements the FIFO mechanism (the element that is inserted first is also deleted first)

**Comment by avinashbest** [comment]
I would like to work on it.

**Comment by abhishekrawe** [comment]
i would  like to work on it

**Comment by avinashbest** [comment]
In which directory I have to push the code? can u guide me?
