### ISSUE TITLE
[NEW Algorithm]DP problems

### ISSUE THREAD

**Issue by Kakarot-2000** [technojam/Ultimate_Algorithms_Repository#256]
**DP problems**
_Dynamic Programming_
1. Wildcard Matching
Given an input string (s) and a pattern (p), implement wildcard pattern matching with support for '?' and '*'.
2. Box Stacking 
LIS variant

**Comment by KalyanKumar-4** [comment]
only algorithm or full program?

**Comment by Kakarot-2000** [comment]
@KalyanKumar-4 I've added the full code.
