### ISSUE TITLE
Prim's Minimum Spanning Tree

### ISSUE THREAD

**Issue by Rituraj-commits** [technojam/Ultimate_Algorithms_Repository#26]
I want to work on this issue

**Comment by ayerhs7** [comment]
Hey! I can do this. Kindly assign this task to me.

**Comment by Harshit564** [comment]
Please assign the issue to me.

**Comment by sdoss93212** [comment]
I added prims algo
with issue number e04b6635b0acd1ff973e25f0820a4b61811521ee

**Comment by princekalra** [comment]
hey please assign me issue
