### ISSUE TITLE
Longest Common Prefix 

### ISSUE THREAD

**Issue by Dipika98** [technojam/Ultimate_Algorithms_Repository#266]
**Title or Name of the Algorithm**
* Longest Common Prefix 

**Describe the algorithm**
 this algorithm returns the longest common prefix string amongst an array of strings.

**Comment by danielskjo** [comment]
Hi @Dipika98 Can I be assigned this algorithm?

**Comment by Dipika98** [comment]
PR #269

**Comment by thezaeemaanwar** [comment]
hi @Dipika98 I want to contribute

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rahulmishra11** [comment]
Please assign this task to me.
