### ISSUE TITLE
Tower Of Hanoi

### ISSUE THREAD

**Issue by umangag07** [technojam/Ultimate_Algorithms_Repository#270]
**Title or Name of the Algorithm**
* Tower Of Hanoi

**Describe the algorithm**
It is basically a puzzle algorithm in which we have 3 rods(A, B, C) and n no of disk . We have to move the whole stack from one rod to different rod. It has few rules-:

1) Only one disk can be moved at a time.
2) Only topmost disk can be shifted to another rod.
3) Bigger disk cannot be placed on smaller disk . 

It is a recursion problem and has **Time complexity of O(2^n -1)**  where n=No of disk 
(How this time complexity came will be explained through mathematical analysis.)

![tower-of-hanoi](https://user-images.githubusercontent.com/52677699/95170543-3c3ba300-07d2-11eb-9612-9ed9231e3e2c.png)

**Comment by krag-harsh** [comment]
can i work on it?

**Comment by umangag07** [comment]
Owners to this repository will assign the issue.

**Comment by umangag07** [comment]
And i have done the code and analysis i am ready to merge if they assign.
