### ISSUE TITLE
Insertion Sort 

### ISSUE THREAD

**Issue by raevi-yadav** [technojam/Ultimate_Algorithms_Repository#273]
Insertion Sort

Insertion sort is a simple sorting algorithm that works similar to the way you sort playing cards in your hands. The array is virtually split into a sorted and an unsorted part. Values from the unsorted part are picked and placed at the correct position in the sorted part.

**Comment by ywalia01** [comment]
Id like to work on this

**Comment by ywalia01** [comment]
Id like to work on this

**Comment by PrathamesR** [comment]
I would like to contribute to this project

**Comment by kashc11** [comment]
I'd like to contribute to this.

**Comment by Rodolfo377** [comment]
I would like to contribute to this project!

**Comment by ghost** [comment]
hey! I can contribute in python. please assign it to me

**Comment by rahulmishra11** [comment]
I want to contribute in C++. Please assign it to me.

**Comment by meghanagottapu** [comment]
I want to contribute this in java.can I work on this? @reliable-raevi

**Comment by MeetMangukiya7** [comment]
I would love to do this. please assign this to me. @reliable-raevi

**Comment by saifali99** [comment]
@reliable-raevi I would like to contribute to this can you assign me this task

**Comment by sharathkumar106** [comment]
Hey! I would like to contribute my code using C language. Please assign me to solve this.
