### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by jain2anki** [technojam/Ultimate_Algorithms_Repository#274]
**Title or Name of the Algorithm**
*Merge Sort*

**Describe the algorithm**
Merge Sort is a Divide and Conquer algorithm. It divides input array in two halves, calls itself for the two halves and then merges the two sorted halves. The merge() function is used for merging two halves. The merge(arr, l, m, r) is key process that assumes that arr[l..m] and arr[m+1..r] are sorted and merges the two sorted sub-arrays into one.

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by gaurangisinha** [comment]
Hello, @jain2anki I want to solve this issue in C++. Could you please assign it to me?

**Comment by rahulmishra11** [comment]
I am really interested to contribute to this. Please assign this task to me.

**Comment by ghost** [comment]
I want to write its code in c++.please assign this to me

**Comment by arpoch** [comment]
I am interested to contribute in c++.

**Comment by theAkashDas** [comment]
hello @jain2anki can I implement this using C ??

**Comment by MeetMangukiya7** [comment]
I  would love to do this task. please assign this to me.
@jain2anki

**Comment by saifali99** [comment]
@jain2anki  could you assign me this task I can do it in C++

**Comment by giTan7** [comment]
can i do it in java?
