### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by jain2anki** [technojam/Ultimate_Algorithms_Repository#275]
**Title or Name of the Algorithm**
*Longest Common Subsequence*

**Describe the algorithm**
Given two sequences, find the length of longest subsequence present in both of them. A subsequence is a sequence that appears in the same relative order, but not necessarily contiguous. For example, “abc”, “abg”, “bdf”, “aeg”, ‘”acefg”, .. etc are subsequences of “abcdefg”.

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rahulmishra11** [comment]
Please Assign this task to me.

**Comment by saifali99** [comment]
I can do this could you assign me this.
