### ISSUE TITLE
Reverse words in a string

### ISSUE THREAD

**Issue by Naziya-Parveen** [technojam/Ultimate_Algorithms_Repository#289]
**Title or Name of the Algorithm**
* Reverse words in a string

**Describe the algorithm**
Reverse all words of a string
eg. input : This is a tree
      output : tree a is This

**Comment by ghsayan** [comment]
would like to solve it in cpp

**Comment by AparnaJuhi** [comment]
I want to solve in Python. Please assign it to me

**Comment by jatinAgarwala** [comment]
Please assign this to me. I will solve it using C
