### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by dhruv-singhal-github** [technojam/Ultimate_Algorithms_Repository#29]
**Title or Name of the Algorithm**
* Quick Sort

**Describe the algorithm**
Quicksort is a highly efficient sorting algorithm and is based on the partitioning of an array or the divide and conquer approach of data into smaller arrays. A large array is partitioned into two arrays one of which holds values smaller than the specified value, say pivot, based on which the partition is made and another array holds values greater than the pivot value.
Quicksort partitions an array and then calls itself recursively twice to sort the two resulting subarrays. This algorithm is quite efficient for large-sized data sets as its average and worst-case complexity are O(N log N) and O(n^2) respectively.

**Comment by dhruv-singhal-github** [comment]
I can solve this issue

**Comment by ishi0301** [comment]
please  assign me this. I would like to do this in C/C++

**Comment by dhruv-singhal-github** [comment]
PR#31 solves this

**Comment by ishi0301** [comment]
@strongrunner can I proceed with it?

**Comment by nits01** [comment]
I have created  #PR for Basic Algorithms Solutions/QuickSort. I have push the algorithm for QuickSort. #68
