### ISSUE TITLE
Doubly Linked list

### ISSUE THREAD

**Issue by rahulatrkm** [technojam/Ultimate_Algorithms_Repository#297]
**Title or Name of the Algorithm**
* Doubly Linked List

**Describe the algorithm**
A Doubly Linked List (DLL) contains an extra pointer, typically called the previous pointer, together with the next pointer and data which are there in a singly linked list.

**Comment by Pankaj05011998** [comment]
Can you assign this to me?

**Comment by rahulatrkm** [comment]
@shreyanshdeep Thank you for assigning this issue to me I have created the pull request for the same. Can you please check?
