### ISSUE TITLE
Bit Manipulation

### ISSUE THREAD

**Issue by iamatul45** [technojam/Ultimate_Algorithms_Repository#327]
**Bit Manipulation**
* Counting Set bits

**Describe the algorithm**
Algorithm uses bit masking techniques to count set bits with complexity of O(1).
 
Can I Work on this ?

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by iamatul45** [comment]
@shreyanshdeep  can you please merge #325 I have added set_bits.cpp file and also added some dynamic programming problems.
hoping your kind reply. 
thank you! : )
