### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by rishabharoraa** [technojam/Ultimate_Algorithms_Repository#35]
**Title or Name of the Algorithm**
Counting Sort

**Describe the algorithm**
The algorithm simply counts the number of occurences of a number in a count array. This count array can be used as a more efficient way to calculate the position of elements in a sorted array when the numbers are small and repetitive.

**Comment by yuktagopalani** [comment]
can i do it?

**Comment by surya7765** [comment]
Can i try to do it?

**Comment by ayerhs7** [comment]
Hey! I would love to do this. Can you please assign this to me?

**Comment by princekalra** [comment]
can u please assign it to me i am happy to conribute in this

**Comment by sakshi0461** [comment]
@RishabhAroraa Can you please assign this issue to me?

**Comment by surya7765** [comment]
Please review my pull request #120
