### ISSUE TITLE
Kosaraju Algorithm

### ISSUE THREAD

**Issue by dhruv-singhal-github** [technojam/Ultimate_Algorithms_Repository#36]
**Title or Name of the Algorithm**
* Kosaraju Algorithm

**Describe the algorithm**
Used to find strongly connected components in a graph.
It is based on the idea that if one is able to reach a vertex v starting from vertex u, then one should be able to reach vertex u starting from vertex v and if such is the case, one can say that vertices u and v are strongly connected - they are in a strongly connected sub-graph.

**Comment by dhruv-singhal-github** [comment]
I would love to work on this

**Comment by dhruv-singhal-github** [comment]
PR #31 solves this

**Comment by sakshi0461** [comment]
@strongrunner Can you please assign this issue to me?
