### ISSUE TITLE
DSA for all languages.

### ISSUE THREAD

**Issue by ashwanisng** [technojam/Ultimate_Algorithms_Repository#4]
We can do DSA in C++, Java, Python, or any other language and anyone who is comfortable with it can contribute.

**Comment by kpiyush04** [comment]
> We can do DSA in C++, Java, Python, or any other language and anyone who is comfortable with it can contribute.

Hi, @ashwanisng Thank You for the suggestion. As per now, we are implementing DSA with C++. We'll definitely consider the suggestion.

Thank You
