### ISSUE TITLE
Prim's Algorithm for minimum spanning tree

### ISSUE THREAD

**Issue by rishabharoraa** [technojam/Ultimate_Algorithms_Repository#42]
**Title or Name of the Algorithm**
Prim's Algorithm for minimum spanning tree

**Describe the algorithm**
Prim's Algorithm is used to find the minimum spanning tree in a graph. It finds the subset of edges that includes every vertex of the graph such that the sum of the weights of the edges can be minimized. Prim's algorithm starts with a single node and explores all the adjacent nodes with all the connecting edges at every step. The edges with the minimal weights causing no cycles in the graph get selected.

**Comment by shreyanshdeep** [comment]
Hey @RishabhAroraa , this issue is already being worked on. :)
