### ISSUE TITLE
Add Egg Dropping Problem

### ISSUE THREAD

**Issue by Hardik0307** [technojam/Ultimate_Algorithms_Repository#44]
**Egg Dropping Problem**

Egg dropping refers to a class of problems in which it is important to find the correct response without exceeding a (low) number of certain failure states. In a toy example, there is a tower of nn floors, and an egg dropper with mm ideal eggs. The physical properties of the ideal egg is such that it will shatter if it is dropped from floor n^*n  or above, and will have no damage whatsoever if it is dropped from floor n^*-1n 
 −1 or below. The problem is to find a strategy such that the egg dropper can determine the floor n^*n  in as few egg drops as possible.

Want to work on this.
Kindly assign me thanks! :+1:

**Comment by Harshit564** [comment]
Assign this issue to me @Hardik0307

**Comment by Hardik0307** [comment]
> Assign this issue to me @Hardik0307

Already made PR.
