### ISSUE TITLE
Depth First Search

### ISSUE THREAD

**Issue by 0xamitdutta** [technojam/Ultimate_Algorithms_Repository#48]
**Title or Name of the Algorithm**
*Depth First Search*

**Describe the algorithm**
Depth-first search (DFS) is an algorithm for traversing or searching tree or graph data structures. The algorithm starts at the root node (selecting some arbitrary node as the root node in the case of a graph) and explores as far as possible along each branch before backtracking.

**Comment by akankshast** [comment]
Please assign this issue to me. I will try my best to improve it.

Regards
Akanksha

**Comment by 0xamitdutta** [comment]
I would like to work on this algorithm

**Comment by 0xamitdutta** [comment]
> Please assign this issue to me. I will try my best to improve it.
> 
> Regards
> Akanksha

Hey, you can open a new issue for Breadth First Search, if that's okay with you.

**Comment by 0xdaya** [comment]
> > Please assign this issue to me. I will try my best to improve it.
> > Regards
> > Akanksha
> 
> Hey, you can open a new issue for Breadth First Search, if that's okay with you.

Hi, I am going to open a issue for bfs to contribute, is that okay?

**Comment by vedanttttt** [comment]
assign this to me , i can do it.

**Comment by Jayesh-Borse** [comment]
Hello Amit,
        I would enjoy contributing to your repository. Please assign me the required task. I'll try my best to complete it as soon as possible and in the best way possible.

Thank you.
Regards.
Jayesh.

**Comment by amanpatel23** [comment]
Hey Amit,
I am eager to work on this.  Please assign this to me.
