### ISSUE TITLE
Kruskal’s Algorithm 

### ISSUE THREAD

**Issue by Sanskar31** [technojam/Ultimate_Algorithms_Repository#50]
**Title or Name of the Algorithm**
 Kruskal’s Algorithm

**Describe the algorithm**
Kruskal's Algorithm finds the minimum spanning tree in an undirected graph in *O(ElogV)*, where E is the number of edges & V is the number of nodes. It falls under a class of algorithms called greedy algorithms that find the local optimum in the hopes of finding a global optimum. We start from the edges with the lowest weight and keep adding edges until we reach our goal.

What is a Spanning Tree?
Given an undirected and connected graph, a spanning tree of the graph  is a tree that spans  (that is, it includes every vertex of ) and is a subgraph of  (every edge in the tree belongs to )

What is a Minimum Spanning Tree?
The cost of the spanning tree is the sum of the weights of all the edges in the tree. There can be many spanning trees. The minimum spanning tree is the spanning tree where the cost is minimum among all the spanning trees. There also can be many minimum spanning trees.

**Comment by Sanskar31** [comment]
Please assign this to me. I will try to give a well commented solution of this problem.

**Comment by Ankitkumarjaiswal** [comment]
hey, I want to work on this issue. Please assign me this.

**Comment by ganeshbhandarkar** [comment]
Please Assign it to me. thank you!

**Comment by siddharthrajaraja** [comment]
@Sanskar31  assign me please

**Comment by Mohit123singh** [comment]
can u plz assign it to me?

**Comment by princekalra** [comment]
hey can i contribute on this
