### ISSUE TITLE
Kahn's Algorithm

### ISSUE THREAD

**Issue by ankur-kayal** [technojam/Ultimate_Algorithms_Repository#55]
**Title or Name of the Algorithm**
Kahn's Algorithm

**Describe the algorithm**

In directed graphs, the most commonly asked question is about to find the **topological sort** of the **directed acyclic graph**. Kahn's Algorithm helps us to find the topological sort of the directed acyclic graph. One special task that Kahn's algorithm achieves is that it can be modified to find the **lexicographically smallest topological sort** of the directed acyclic graph.

Kahn's algorithm uses indegree of the vertices to find the topological sort.

Those who dont know what a topological sort is: 
A topological sort or topological ordering of a directed graph is a linear ordering of its vertices such that for every directed edge uv from vertex u to vertex v, u comes before v in the ordering.

**Comment by ankur-kayal** [comment]
Please assign me this issue. I can write a detailed explanation of the algorithms along with the different tasks that can be achived with the different implementations.

**Comment by amishaagarwal1998** [comment]
Please assign to me! I can explain it well, along with the code.

**Comment by sakshi0461** [comment]
@ankur-kayal Can you please assign this issue to me?

**Comment by princekalra** [comment]
hey can i contribute on this

**Comment by ankur-kayal** [comment]
@shreyanshdeep Pull request added 👍

**Comment by ankur-kayal** [comment]
@shreyanshdeep  can you merge my request? If not, please tell me the issues 👍
