### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by crypticani** [technojam/Ultimate_Algorithms_Repository#82]
I want to contribute the repo with some programs in C language for sorting algorithms.
These are:
1. Bubble sort
2. Selection sort
3. Insertion sort
4. Quick sort
5. Merge sort

**Comment by icecreamcake101** [comment]
i'd like to grab this

**Comment by crypticani** [comment]
I have forked this repo and will request a PR soon.

**Comment by M-Akhil-pavan-sai** [comment]
can i contribute to this ? should i create a folder or is there any folder to upload the file.

**Comment by tista123** [comment]
Can I contribute to this issue?

**Comment by sakshi0461** [comment]
@crypticani Can you please assign this issue to me?

**Comment by shreyanshdeep** [comment]
@crypticani  can you do it in c++ ??

**Comment by crypticani** [comment]
@shreyanshdeep Sorry, but I only code in C, Python, Java and C#.

**Comment by AyushRajSharma** [comment]
i can do it in c , c++, python.
if it is still not assigned assign me.

**Comment by satyamsaran** [comment]
I can add all the sorting algos like bubble, insertion, selection, quick, merge(iterative and recursive), count, bin/bucket, radix and shell sort.
I code in c++. 
Please assign me this task.

**Comment by AyushRajSharma** [comment]
Added sorting algorithm #169

**Comment by princekalra** [comment]
i want to work  on this please assign it to me
