### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by M-Akhil-pavan-sai** [technojam/Ultimate_Algorithms_Repository#87]
**Title or Name of the Data Structure**
A linked list is a linear data structure where each element is a separate object.
Linked list elements are not stored at contiguous location; the elements are linked using pointers.

**Describe the Data Structure**
Each node of a list is made up of two items - the data and a reference to the next node. The last node has a reference to null. The entry point into a linked list is called the head of the list. It should be noted that head is not a separate node, but the reference to the first node. If the list is empty then the head is a null reference.

**Applications of Linked List**
1. Image viewer – Previous and next images are linked, hence can be accessed by next and previous button.
2.Previous and next page in web browser – We can access previous and next url searched in web browser by pressing back and next button since, they are linked as linked list.
3. Music Player – Songs in music player are linked to previous and next song. you can play songs either from starting or ending of the list.
4.Implementation of stacks and queues
5. Implementation of graphs : Adjacency list representation of graphs is most popular which is uses linked list to store adjacent vertices.
6. Dynamic memory allocation : We use linked list of free blocks.
7. Maintaining directory of names
8. Performing arithmetic operations on long integers
9. Manipulation of polynomials by storing constants in the node of linked list

**Comment by M-Akhil-pavan-sai** [comment]
I would like to contribute code for Linked List Data Structure in C++

**Comment by sakshi0461** [comment]
@M-Akhil-pavan-sai Can you please assign this issue to me?

**Comment by RAJAT-SOUL** [comment]
I would like to add the easier version of the linked list so that one can understand the real working of how do elements move.

**Comment by dalalvarun** [comment]
Please assign this to me. I am efficient in Linked Lists. (Linear LL using Arrays, Linear, Circular, Doubly Linked, Circular Doubly-Linked, Header Linked List and Polynomial Representation using Linked Lists)

**Comment by shreyanshdeep** [comment]
Hey @M-Akhil-pavan-sai , before pushing your code, create 2 folders. 
1. Data structures
2. Inside 1st folder create a linked list named folder and add your code into this

**Comment by M-Akhil-pavan-sai** [comment]
@shreyanshdeep Thank you for assigning ,I will do my best.

**Comment by M-Akhil-pavan-sai** [comment]
PR raised - #171

**Comment by akhil-singh-parmar** [comment]
please assign me this issue I will add all the required algorithms for reversing linked list , finding loop and removing loop .
