### ISSUE TITLE
Dynamic Programming

### ISSUE THREAD

**Issue by iamatul45** [technojam/Ultimate_Algorithms_Repository#90]
**Dynamic Programming**
* Knapsack Algorithm

**1.Fractional Knapsack Problem**
This is more of Greedy algorithm than dynamic programming

**2. 0/1 Knapsack Problem**
This is pure dynamic programming . Many problem are there to solve using this. Eg. Subset sum, Subset difference, Target Sum.

**3. Unbounded Knapsack Problem**
The main difference here is we allow repetition of items as compared to 0/1 Knapsack which allow item to be put once only. Eg. Rod Cutting Problem

I want to contribute to this algorithms. can I?

**Comment by njain794** [comment]
you can contribute but 
1. add comments wherever needed
2. try adding recursive , top-down , bottom up approach for the 3 knapsack problems

**Comment by iamatul45** [comment]
> you can contribute but
> 
> 1. add comments wherever needed
> 2. try adding recursive , top-down , bottom up approach for the 3 knapsack problems

**Comment by sakshi0461** [comment]
@iamatul45 Can you please assign this issue to me?

**Comment by iamatul45** [comment]
> @iamatul45 Can you please assign this issue to me?

@sakshi0461 Yes you can contribute.

**Comment by nanusharma2001** [comment]
can you assign this issue to me?

**Comment by princekalra** [comment]
hey can i contribute on this
