### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by rsrahul1000** [technojam/Ultimate_Algorithms_Repository#91]
**Dynamic Programming**
* Kadane's Algorithm

**Description**
An efficient way to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Comment by rsrahul1000** [comment]
Can you please assign this issue to me? I would love to work on it.
It will be useful for coding test preparation which involves dynamic programming :)

**Comment by sakshi0461** [comment]
@rsrahul1000 Can you please assign this issue to me?

**Comment by zahinekbal** [comment]
@rsrahul1000 can you please assign this issue to me .....
i am working on it ......

**Comment by sanchit000** [comment]
Can you please assign this issue to me? I would love to work on it.

**Comment by rsrahul1000** [comment]
The Kadane's Algorithm has been already merged #93 
Feel free to add an issue for a new algorithm you guys want to add to this repository.
Only the owner or a collaborator of the repository can assign the issue to the people who are requesting it.

As of now, I am closing this issue :)
