### ISSUE TITLE
Counting Subarray with equal zeros and ones

### ISSUE THREAD

**Issue by tapanchudasama7** [technojam/Ultimate_Algorithms_Repository#92]
**Title or Name of the Algorithm**
Count number of Subarrays with Equal Zero and Ones

**Describe the algorithm**

1. Take a variable currSum.
2. Take the sum of the entire array considering all zeroes as -1 and 1 as 1.
3. Simultaneously keep updating the value of hashmap as you traverse through the array. 
4. Now traverse through the hashmap and look if any value of currSum appears more than once. 
   Why do we do this?
   
   Imagine an array like this: [1, 0, 0, 1, 0, 1, 1]
   Making all zeroes as -1.
   [1, -1, -1, 1, -1, 1, 1]

   Now the hashmap would have values such as this: 
   -1 --- 2
    0 --- 3
    1 --- 2

5. Now as if we encounter the same sum more than twice, that means the value of the subarray between the two indices is zero. So we add that to our answer.
6. Finally add the hashmap value of 0 to our answer as the subarray with zero-sum also need to be counted.

**Comment by imsubhra** [comment]
@inflame07  Can you please assign this issue to me? I would love to work on it.

**Comment by sakshi0461** [comment]
@inflame07 Can you please assign this issue to me?

**Comment by akshat235** [comment]
@inflame07 Hello, please assign this issue to me.

**Comment by sanchit000** [comment]
I would like to work on this issue.

**Comment by akshat235** [comment]
Please assign this to me.
