### ISSUE TITLE
Sieve of Eratosthenes 

### ISSUE THREAD

**Issue by varshatumburu** [technojam/Ultimate_Algorithms_Repository#94]
**Algorithm**
* Finds all prime numbers under n 

**Description**
Python program to print all primes smaller than or equal to n using Sieve of Eratosthenes.

**Comment by sakshi0461** [comment]
Claim

**Comment by Sankalpagrawal** [comment]
Hi Please assign this to me

**Comment by akshat235** [comment]
Hello, please assign this to me.

**Comment by ravisaxena23** [comment]
Hey @Sankalpagrawal  @akshat235 @sakshi0461 please work whoever finish first we will merge it, for other pr we won't reject them if they are correct no issue

**Comment by karan-kunwar** [comment]
@varshatumburu I would like to make this program.

**Comment by varshatumburu** [comment]
Thank you all, but I have already worked upon this.

**Comment by akshat235** [comment]
Hi! @ravisaxena23  Submitted a pull request as mentioned above.
